[pytest]
testpaths = tests
filterwarnings =
    ignore:n_fft=.*is too large for input signal:UserWarning
    ignore:PySoundFile failed:UserWarning
    ignore:Trying to estimate tuning from empty frequency set:UserWarning
